### ISSUE TITLE
Loading Aminmation on iOS App

### ISSUE THREAD

**Issue by garyak** [atomic7777/atomic_calendar#4]
When atomic_calendar is displayed on the iOS Companion App (v1.5 & 2.0), the loading animation runs until the app is manually refreshed. This typically occurs when the calendar app has been in the background for several minutes. Once refreshed, the calendar loads and the animation disappears. This behavior does not occur with Firefox on the PC.  Hass.io 89.0, iPhone 8 iOS12.1.4

**Comment by atomic7777** [comment]
Has this been the case from the start, and always, or only sometimes? I will try to get to what the problem is. While the icon is visible, the application tries to load data in the background (because getting calendar data from Google takes some time, it shouldn't block the rest of the Home Assistant). It's a common method of JavaScript and HomeAssistant.
I don't know the CompanionApp and don't have any iOS device, so it will be hard, but I'll try too investigate the problem.

**Comment by garyak** [comment]
No longer an issue with this add-on.
